default_context:
  name: "openpilot-alpine"
  version: "0.1.0"
  slug: "openpilot_alpine"
  command: "openpilot-alpine"
  cli: "argparse"
  config: "y"
  compat: "custom"
  jupyter: "n"
  sqlite: "y"
  pypy: "y"
  travis: "n"
  appveyor: "n"
  description: "OpenPilot for Alpine Docker"
  author: "Achilles Rasquinha"
  email: "achillesrasquinha@gmail.com"
  keywords: "openpilot docker alpine"
  license: "MIT License"
  repo_service: "https://github.com"
  repo_service_username: "achillesrasquinha"
  repo_service_reponame: "openpilot-alpine"
  docker_service_username: "achillesrasquinha"
  docker_service_reponame: "openpilot-alpine"
  github_action: "n"
  ml: "n"
  editor: "vscode"
  url: "https://github.com/achillesrasquinha/openpilot-alpine"